### CREATE Place
POST http://localhost:5000/api/places 
content-type: application/json

{ 
    "title":"FNB stadium",
    "description":"Famous soccer stadium",
    "address": "Soccer City Ave, Nasrec, Johannesburg, 2147",
    "creator":"631b36fae0eccac29c797a64"
}

###Find place
GET http://localhost:5000/api/places/631307b9d1473bb8e856e231

###Find users places
GET http://localhost:5000/api/places/user/u2

###Updating Place
PATCH http://localhost:5000/api/places/631307b9d1473bb8e856e231
content-type: application/json

{ 
    "title":"FNB stadium",
    "description":"Kazier Chiefs stadium"
}

###Deleting Place
DELETE http://localhost:5000/api/places/631b395e957f9c4776b42dd4

###Creating a User
POST http://localhost:5000/api/users/signup
content-type: application/json

{
    "name":"Jerry",
    "email":"JerryWerrygmail.com",
    "password":"test@2234",
    "image":"https://i.pinimg.com/originals/0f/ca/a1/0fcaa1dcca650f50648826da8300e46d.jpg"
}


###Loging in
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email":"jerryferry@gmail.com",
    "password":"test@2234"
}


###Get users
GET http://localhost:5000/api/users/